language: c
env:
  - OCAML_VERSION=4.06
matrix:
  include:
    - env: SATYSFI_TARGET='windows32'
      os: linux
      dist: trusty
      # sudo: false
      sudo: required
      compiler: gcc
    - env: SATYSFI_TARGET='windows64'
      os: linux
      dist: trusty
      # sudo: false
      sudo: required
      compiler: gcc
addons:
  apt:
    packages:
      - gcc-mingw-w64-x86-64
      - gcc-mingw-w64-i686
      - libc6-dev-i386
      - gcc-multilib
      - aspcud
install:
  - ./.travis/setup-opam.sh
  - ./.travis/deps.sh
script:
  - ./.travis/build.sh
